version = 0.1

[default.deploy.parameters]
stack_name = "archflow"
resolve_s3 = true
s3_prefix = "archflow"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = "Environment=\"dev\""
